name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev ffmpeg
          sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
          pip install -r app/requirements.txt
      - name: Build
        run: flet build linux
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: app/dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install flet
        run: |
          choco install git
          choco install flutter
      - name: Install dependencies
        run: |
          choco install ffmpeg
          pip install -r app/requirements.txt
      - name: Build
        run: flet build windows
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: app/dist/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          brew update
          brew install ffmpeg
          pip install -r app/requirements.txt
      - name: Build
        run: pyinstaller --onefile src/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: dist/
